import React, { useEffect, useState } from "react";
import Person from "./component/person/Person";

const App = () => {
  const [isVisible, setIsVisible] = useState(true); // laver state og set variable som er "True"

  useEffect(() => {
    document.title = isVisible ? 'Show Person' : 'Hide Person'; // hvis state variable isVisible er "True" så vises 'Show Person' elles så vises 'Hide Person' i document title
  }, [isVisible]); // reload page hvergange state variable 'isVisible' ændre sig.


  return (
    <div className="container text-center p-5">
      {/* Laver en toggle button der har Onclick function som kigge efter 'isVisible' state. hver gange user click på button, state variable ændre til "True" eller "False" */}
      <button className="btn btn-outline-info" onClick={() => setIsVisible(!isVisible)}>Toggle Show Person</button> 

      {/* hvis isVisible state er "True", skal den så viser de der er inholde i 'div' */}
      {isVisible && (
        <article className="row py-5">
          <section className="RGB2 col-2 p-3" >
            <Person name="John" /> {/* 'Person' component har 'name' prop. Bruge sammen component men ændre props navn for at vise forskillige navn på siden */}
          </section>
          <section className="RGB3 col-2 p-3" ><Person name="Alex" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Danny" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Michael" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Aksel" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Noah" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Ida" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Frederik" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Christian" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Emil" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Malthe" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Erik" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Anna" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Mikkel" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Alfred" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Mads" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Johan" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Rasmus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Ella" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Magnus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Oscar" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Alberte" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Asger" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Carl" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Elias" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Alex" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Danny" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Michael" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Aksel" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Noah" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Ida" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Frederik" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Christian" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Emil" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Marcus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Erik" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Anna" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Mikkel" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Mads" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Johan" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Rasmus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Ella" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Magnus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Oscar" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Alberte" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Asger" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Carl" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Elias" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Alex" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Danny" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Aksel" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Noah" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Ida" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Frederik" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Christian" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Emil" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Malthe" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Erik" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Mikkel" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB2 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB1 col-2 p-3" ><Person name="Markus" /></section>
          <section className="RGB3 col-2 p-3" ><Person name="Markus" /></section>

      </article>
      )}
    </div>
  );
}

export default App;
